version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
    command: ["--wiredTigerCacheSizeGB", "2"]

  wishlist-app:
    image: elusiuve/wishlist:latest
    container_name: wishlist-app
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/database?authSource=admin&authMechanism=SCRAM-SHA-256
    restart: unless-stopped
    depends_on:
      - mongo

